version: "3.3"

services:
        db_mysql:
                image: mysql
                container_name: db_mysql
                ports:
                        - "3306:3306"
                environment:
                        MYSQL_DATABASE: testapp
                        MYSQL_ROOT_PASSWORD: helloworld
                        MYSQL_USER: testuser
                        MYSQL_PASSWORD: testpassword
                volumes:
                        - ./db:/docker-entrypoint-initdb.d/:ro
        app.py:
                build: .
                container_name: app.py
                depends_on:
                        - db_mysql
                links:
                        - db_mysql:db_mysql
                ports:
                        - "5000:5000"
        
